#!/usr/bin/env node
// var name = process.argv[2];
// var exec = require("child_process").exec;

const { rm } = require("shelljs");

// var child = exec("echo hello " + name, function (err, stdout, stderr) {
//   if (err) throw err;
//   console.log(stdout);
// });

// var name = process.argv[2];
// var shell = require("shelljs");

// shell.exec("echo hello " + name);

// require("shelljs/global");

// if (!which("git")) {
//   echo("Sorry, this script requires git");
//   exit(1);
// }

// mkdir("-p", "out/Release");
// cp("-R", "stuff/*", "out/Release");

// cd("lib");
// ls("*.js").forEach(function (file) {
//   sed("-i", "BUILD_VERSION", "v0.1.2", file);
//   sed("-i", /.*REMOVE_THIS_LINE.*\n/, "", file);
//   sed("-i", /.*REPLACE_LINE_WITH_MACRO.*\n/, cat("macro.js"), file);
// });
// cd("..");

// if (exec('git commit -am "Auto-commit"').code !== 0) {
//   echo("Error: Git commit failed");
//   exit(1);
// }
